apiVersion: apps/v1
kind: Deployment
metadata:
  name: hitesh-k8s-deploy
  labels:
    app: hitesh-k8s-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hitesh-k8s-app
  template:
    metadata:
      labels:
        app: hitesh-k8s-app
    spec:
      containers:
      - name: hitesh-k8s-container
        image: 11054352/pl-javawebappimg
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hitesh-k8s-np-service
  labels:
    app: hitesh-k8s-app
spec:
  selector:
    app: hitesh-k8s-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
